#ifndef CONFIG_H
#define CONGIG_H

#define KERNEL_CODE_SELECTOR 0x08
#define KERNEL_DATA_SELECTOR 0x10

#define PINEOS_TOTAL_INTERRUPTS 512  /* 0x200 */

// 100 MB size
#define PINEOS_HEAP_SIZE_BYTES  	104857600
#define PINEOS_HEAP_BLOCK_SIZE  	4096
#define PINEOS_HEAP_ADDRESS 		0x01000000
#define PINEOS_HEAP_TABLE_ADDRESS 	0x00007E00

#define PINEOS_SECTOR_SIZE          512


#define PINEOS_MAX_PATH                  108
#define PINEOS_TOTAL_GDT_SEGMENTS          6
#define PINEOS_MAX_PROGRAM_ALLOCATIONS  1024
#define PINEOS_MAX_PROCESSES             12

#define PINEOS_PROGRAM_VIRTUAL_ADDRESS              0x400000
#define PINEOS_USER_PROGRAM_STACK_SIZE              (1024 * 16)
#define PINEOS_PROGRAM_VIRTUAL_STACK_ADDRESS_START  0x3FF000
#define PINEOS_PROGRAM_VIRTUAL_STACK_ADDRESS_END    (PINEOS_PROGRAM_VIRTUAL_STACK_ADDRESS_START - PINEOS_USER_PROGRAM_STACK_SIZE)

#define USER_DATA_SEGMENT  0x23     // Offset in the real GDT table
#define USER_CODE_SEGMENT  0x1B     // Offset in the real GDT table


#define PINEOS_MAX_ISR80H_COMMANDS 		1024

#endif /* CONFIG_H */